version: '3.8'

services:
  app:
    image: openjdk:23-jdk
    container_name: spring-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    command: ["java", "-jar", "app.jar"]

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
